version: "3.7"

services:
  myapitemplate:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: my-template
    restart: always
    env_file:
      - .env
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
